dist: trusty
sudo: required

os:
  - linux
  - osx

language: cpp

compiler: 
  - gcc
  - clang
  
env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release
  
matrix:
  exclude:
    - os: osx
      compiler: gcc      
    - os: osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    - os: osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release
  
before_install:
  - echo $TRAVIS_OS_NAME
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update -qq; fi
  
install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew upgrade cmake; fi
  
script:
  - mkdir build
  - cd ./build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DBUILD_TESTS=YES
  - make
  - cd ./test
  - ./Test --rng-seed time
